/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/audit-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Audit Events
         * @description The caller's own tenant's audit events, newest first. Reading is itself audited.
         */
        get: operations["list_audit_events_api_v1_audit_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Cases
         * @description The caller's own tenant's cases, newest first.
         */
        get: operations["list_cases_api_v1_cases_get"];
        put?: never;
        /**
         * Create Case
         * @description Create a case. Only a legal or trading name is required; the rest is tracked as gaps.
         */
        post: operations["create_case_api_v1_cases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Case
         * @description One case. Viewing Restricted case content is itself audited.
         */
        get: operations["get_case_api_v1_cases__case_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Case
         * @description Change some fields. Send `expected_version`; a stale one returns 409 and saves nothing.
         */
        patch: operations["update_case_api_v1_cases__case_id__patch"];
        trace?: never;
    };
    "/api/v1/cases/{case_id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents */
        get: operations["list_documents_api_v1_cases__case_id__documents_get"];
        put?: never;
        /**
         * Upload Document
         * @description Upload a financial statement, credit report or supporting file. The file is checked by its
         *     contents, virus-scanned and only then stored under a random name in private storage.
         */
        post: operations["upload_document_api_v1_cases__case_id__documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{case_id}/documents/{document_id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Document
         * @description Download as an attachment. The browser is told never to display or sniff the content.
         */
        get: operations["download_document_api_v1_cases__case_id__documents__document_id__content_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{case_id}/draft-recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Drafts
         * @description The case's drafts, newest first. Older drafts are kept; nothing is overwritten.
         */
        get: operations["list_drafts_api_v1_cases__case_id__draft_recommendations_get"];
        put?: never;
        /**
         * Import Draft
         * @description Record a draft recommendation written by an analyst session (assisted mode). The server
         *     derives the outcome and amount from the approved policy; the author cannot choose them.
         */
        post: operations["import_draft_api_v1_cases__case_id__draft_recommendations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{case_id}/draft-recommendations/{draft_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Draft */
        get: operations["get_draft_api_v1_cases__case_id__draft_recommendations__draft_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{case_id}/entity-candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Candidates */
        get: operations["list_candidates_api_v1_cases__case_id__entity_candidates_get"];
        put?: never;
        /**
         * Add Candidate
         * @description Add a plausible legal entity. Two or more open candidates make the case ambiguous.
         */
        post: operations["add_candidate_api_v1_cases__case_id__entity_candidates_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{case_id}/entity-resolution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve Entity
         * @description A person chooses the one exact legal entity. This is the only way a case becomes resolved.
         */
        post: operations["resolve_entity_api_v1_cases__case_id__entity_resolution_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{case_id}/entity-resolution/reopen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reopen Entity
         * @description Override a resolved entity. A reason is mandatory; the reopening is audited and logged.
         */
        post: operations["reopen_entity_api_v1_cases__case_id__entity_resolution_reopen_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{case_id}/entity-resolution/unconfirmed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record Entity Unconfirmed
         * @description A person records that the legal entity could not be confirmed or found. A reason is
         *     mandatory; it is kept in the append-only resolution log and the action is audited.
         */
        post: operations["record_entity_unconfirmed_api_v1_cases__case_id__entity_resolution_unconfirmed_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{case_id}/research-readiness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Research Readiness
         * @description Whether research may start, and the plain-language reason if not (AC-01).
         */
        get: operations["get_research_readiness_api_v1_cases__case_id__research_readiness_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Who the caller is and what they may do. Informational; grants nothing.
         */
        get: operations["me_api_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness check. Reports service status only; no case or tenant data.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuditEventOut */
        AuditEventOut: {
            /** Action */
            action: string;
            /** Actor */
            actor: string | null;
            /** Correlation Id */
            correlation_id: string;
            /** Details */
            details: {
                [key: string]: string;
            };
            /** Id */
            id: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Outcome */
            outcome: string;
            /** Resource Id */
            resource_id: string | null;
            /** Resource Type */
            resource_type: string | null;
        };
        /**
         * Band
         * @enum {string}
         */
        Band: "FULL" | "REDUCED" | "DECLINE";
        /** Blocker */
        Blocker: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** Body_upload_document_api_v1_cases__case_id__documents_post */
        Body_upload_document_api_v1_cases__case_id__documents_post: {
            category: components["schemas"]["DocumentCategory"];
            /** File */
            file: string;
        };
        /**
         * CandidateCreate
         * @description A plausible legal entity for the case. Only the legal name is required.
         */
        CandidateCreate: {
            /** Address */
            address?: string | null;
            /** Aliases */
            aliases?: string[];
            /** Former Names */
            former_names?: string[];
            /** Jurisdiction */
            jurisdiction?: string | null;
            /** Legal Name */
            legal_name: string;
            /** Parent Name */
            parent_name?: string | null;
            /** Registration Number */
            registration_number?: string | null;
            /** Subsidiaries */
            subsidiaries?: string[];
            /** Website */
            website?: string | null;
        };
        /** CandidateOut */
        CandidateOut: {
            /** Address */
            address?: string | null;
            /** Aliases */
            aliases?: string[];
            /**
             * Case Id
             * Format: uuid
             */
            case_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Created By */
            created_by: string;
            /** Former Names */
            former_names?: string[];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Jurisdiction */
            jurisdiction?: string | null;
            /** Legal Name */
            legal_name: string;
            /** Parent Name */
            parent_name?: string | null;
            /** Registration Number */
            registration_number?: string | null;
            /** Source */
            source: string;
            state: components["schemas"]["CandidateState"];
            /** Subsidiaries */
            subsidiaries?: string[];
            /** Website */
            website?: string | null;
        };
        /**
         * CandidateState
         * @enum {string}
         */
        CandidateState: "candidate" | "selected" | "rejected";
        /** CaseCreate */
        CaseCreate: {
            /** Address */
            address?: string | null;
            /** Context */
            context?: string | null;
            /** Exposure Amount */
            exposure_amount?: number | string | null;
            /**
             * Exposure Currency
             * @description ISO 4217, e.g. CAD
             */
            exposure_currency?: string | null;
            /** Industry */
            industry?: string | null;
            /** Jurisdiction */
            jurisdiction?: string | null;
            /** Legal Name */
            legal_name?: string | null;
            /** Parent Name */
            parent_name?: string | null;
            /** Registration Number */
            registration_number?: string | null;
            /** Terms */
            terms?: string | null;
            /** Trading Name */
            trading_name?: string | null;
            /** Ubo Name */
            ubo_name?: string | null;
            /** Website */
            website?: string | null;
        };
        /** CaseOut */
        CaseOut: {
            /** Address */
            address?: string | null;
            /** Context */
            context?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Exposure Amount */
            exposure_amount?: string | null;
            /**
             * Exposure Currency
             * @description ISO 4217, e.g. CAD
             */
            exposure_currency?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Industry */
            industry?: string | null;
            /** Information Gaps */
            information_gaps: components["schemas"]["InformationGap"][];
            /** Jurisdiction */
            jurisdiction?: string | null;
            /** Legal Name */
            legal_name?: string | null;
            /** Owner */
            owner: string;
            /** Parent Name */
            parent_name?: string | null;
            /** Registration Number */
            registration_number?: string | null;
            /** Resolved At */
            resolved_at?: string | null;
            /** Resolved By */
            resolved_by?: string | null;
            /** Resolved Candidate Id */
            resolved_candidate_id?: string | null;
            status: components["schemas"]["CaseStatus"];
            /** Terms */
            terms?: string | null;
            /** Trading Name */
            trading_name?: string | null;
            /** Ubo Name */
            ubo_name?: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version */
            version: number;
            /** Website */
            website?: string | null;
        };
        /**
         * CaseStatus
         * @description Phase 1 statuses. Later phases add research and review statuses.
         * @enum {string}
         */
        CaseStatus: "DRAFT" | "ENTITY_AMBIGUOUS" | "ENTITY_RESOLVED" | "ENTITY_UNCONFIRMED";
        /**
         * CaseUpdate
         * @description Partial update. `expected_version` guards against overwriting someone else's change.
         */
        CaseUpdate: {
            /** Address */
            address?: string | null;
            /** Context */
            context?: string | null;
            /** Expected Version */
            expected_version: number;
            /** Exposure Amount */
            exposure_amount?: number | string | null;
            /**
             * Exposure Currency
             * @description ISO 4217, e.g. CAD
             */
            exposure_currency?: string | null;
            /** Industry */
            industry?: string | null;
            /** Jurisdiction */
            jurisdiction?: string | null;
            /** Legal Name */
            legal_name?: string | null;
            /** Parent Name */
            parent_name?: string | null;
            /** Registration Number */
            registration_number?: string | null;
            /** Terms */
            terms?: string | null;
            /** Trading Name */
            trading_name?: string | null;
            /** Ubo Name */
            ubo_name?: string | null;
            /** Website */
            website?: string | null;
        };
        /**
         * DeclineFinding
         * @description A finding that always means decline, but only once verified under the protocol.
         */
        DeclineFinding: {
            /**
             * Code
             * @enum {string}
             */
            code: "insolvency" | "sanctions" | "fraud_or_regulatory" | "going_concern";
            /** Evidence */
            evidence: components["schemas"]["EvidenceRef"][];
            /** Verified */
            verified: boolean;
        };
        /**
         * DocumentCategory
         * @enum {string}
         */
        DocumentCategory: "financial_statement" | "credit_report" | "supporting";
        /**
         * DocumentOut
         * @description What the API returns about an uploaded document. Never the storage location.
         */
        DocumentOut: {
            /**
             * Case Id
             * Format: uuid
             */
            case_id: string;
            category: components["schemas"]["DocumentCategory"];
            /** Content Type */
            content_type: string;
            /** Filename */
            filename: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Scan Status */
            scan_status: string;
            /** Sha256 */
            sha256: string;
            /** Size Bytes */
            size_bytes: number;
            /**
             * Uploaded At
             * Format: date-time
             */
            uploaded_at: string;
            /** Uploaded By */
            uploaded_by: string;
        };
        /** DraftImport */
        DraftImport: {
            /** Ai Proposed Amount */
            ai_proposed_amount?: number | string | null;
            /** Decline Findings */
            decline_findings?: components["schemas"]["DeclineFinding"][];
            /** Factors */
            factors?: components["schemas"]["Factor"][];
            /** Financial Findings Weak */
            financial_findings_weak: boolean;
            /** Information Gaps */
            information_gaps?: string[];
            /** Reasons */
            reasons: components["schemas"]["Reason"][];
            source: components["schemas"]["SourceInfo"];
            /** Summary */
            summary: string;
        };
        /**
         * DraftOut
         * @description A draft recommendation for the underwriter. Always labelled; never a decision.
         */
        DraftOut: {
            /** Ai Proposed Amount */
            ai_proposed_amount: string | null;
            band: components["schemas"]["Band"];
            /**
             * Case Id
             * Format: uuid
             */
            case_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Created By */
            created_by: string;
            /** Decline Findings */
            decline_findings: components["schemas"]["DeclineFinding"][];
            /** Factors */
            factors: components["schemas"]["Factor"][];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Information Gaps */
            information_gaps: string[];
            /** Limitations */
            limitations: string[];
            /**
             * Notice
             * @default Draft recommendation for the underwriter. Not a decision.
             */
            notice: string;
            outcome: components["schemas"]["Outcome"];
            /** Policy Version */
            policy_version: string;
            /** Reasons */
            reasons: components["schemas"]["Reason"][];
            /** Recommended Amount */
            recommended_amount: string | null;
            /** Requested Amount */
            requested_amount: string | null;
            /** Requested Currency */
            requested_currency: string | null;
            /** Rule Codes */
            rule_codes: string[];
            source: components["schemas"]["SourceInfo"];
            /** Summary */
            summary: string;
            /**
             * Test Product
             * @default true
             */
            test_product: boolean;
            /** Version */
            version: number;
        };
        /** ErrorBody */
        ErrorBody: {
            /** Code */
            code: string;
            /** Correlation Id */
            correlation_id: string;
            /** Field Errors */
            field_errors?: components["schemas"]["FieldError"][] | null;
            /** Message */
            message: string;
            /** Retryable */
            retryable: boolean;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        /**
         * EvidenceRef
         * @description Where a reason comes from. Documents must be real uploads of this case; web sources need a
         *     secure address, the date it was read, and the quoted words.
         */
        EvidenceRef: {
            /** Document Id */
            document_id?: string | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "document" | "web";
            /** Location */
            location?: string | null;
            /** Quote */
            quote: string;
            /** Retrieved At */
            retrieved_at?: string | null;
            /** Url */
            url?: string | null;
        };
        /**
         * Factor
         * @description Something that lowered the proposed amount, and how.
         */
        Factor: {
            /**
             * Code
             * @enum {string}
             */
            code: "sector_outlook" | "acceptable_not_strong" | "missing_information" | "concentration";
            /** Explanation */
            explanation: string;
        };
        /** FieldError */
        FieldError: {
            /** Field */
            field: string;
            /** Message */
            message: string;
        };
        /** Health */
        Health: {
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /** InformationGap */
        InformationGap: {
            /** Description */
            description: string;
            /** Field */
            field: string;
        };
        /** Me */
        Me: {
            /** Permissions */
            permissions: string[];
            /** Roles */
            roles: string[];
            /** Subject */
            subject: string;
            /** Tenant Id */
            tenant_id: string;
        };
        /**
         * Outcome
         * @enum {string}
         */
        Outcome: "APPROVE" | "DECLINE";
        /** Readiness */
        Readiness: {
            /** Allowed */
            allowed: boolean;
            /** Blockers */
            blockers: components["schemas"]["Blocker"][];
            status: components["schemas"]["CaseStatus"];
        };
        /** Reason */
        Reason: {
            /** Evidence */
            evidence: components["schemas"]["EvidenceRef"][];
            /** Text */
            text: string;
        };
        /**
         * ReopenRequest
         * @description Reopening a resolved entity is an override, so a reason is mandatory.
         */
        ReopenRequest: {
            /** Reason */
            reason: string;
        };
        /**
         * ResolveRequest
         * @description The human choice of the one exact legal entity.
         */
        ResolveRequest: {
            /**
             * Candidate Id
             * Format: uuid
             */
            candidate_id: string;
            /** Note */
            note?: string | null;
        };
        /**
         * SourceInfo
         * @description Who produced the draft and with what, so the run can be reproduced (P-10).
         */
        SourceInfo: {
            /**
             * Kind
             * @constant
             */
            kind: "claude_code_session";
            /** Model */
            model: string;
            /** Policy Version */
            policy_version: string;
            /** Skill Version */
            skill_version: string;
        };
        /**
         * UnconfirmedRequest
         * @description A person records that the legal entity could not be confirmed or found (reason required).
         */
        UnconfirmedRequest: {
            /** Reason */
            reason: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_audit_events_api_v1_audit_events_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEventOut"][];
                };
            };
            /** @description Not signed in, or the token is invalid. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Signed in but not permitted. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found (or belongs to another tenant). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request was malformed. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_cases_api_v1_cases_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseOut"][];
                };
            };
            /** @description Not signed in, or the token is invalid. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Signed in but not permitted. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found (or belongs to another tenant). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request was malformed. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_case_api_v1_cases_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaseCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseOut"];
                };
            };
            /** @description Not signed in, or the token is invalid. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Signed in but not permitted. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found (or belongs to another tenant). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request was malformed. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_case_api_v1_cases__case_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseOut"];
                };
            };
            /** @description Not signed in, or the token is invalid. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Signed in but not permitted. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found (or belongs to another tenant). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request was malformed. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_case_api_v1_cases__case_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaseUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseOut"];
                };
            };
            /** @description Not signed in, or the token is invalid. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Signed in but not permitted. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found (or belongs to another tenant). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request was malformed. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_documents_api_v1_cases__case_id__documents_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"][];
                };
            };
            /** @description Not signed in, or the token is invalid. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Signed in but not permitted. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found (or belongs to another tenant). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request was malformed. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    upload_document_api_v1_cases__case_id__documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_api_v1_cases__case_id__documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"];
                };
            };
            /** @description Not signed in, or the token is invalid. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Signed in but not permitted. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found (or belongs to another tenant). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request was malformed. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    download_document_api_v1_cases__case_id__documents__document_id__content_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Not signed in, or the token is invalid. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Signed in but not permitted. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found (or belongs to another tenant). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request was malformed. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_drafts_api_v1_cases__case_id__draft_recommendations_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftOut"][];
                };
            };
            /** @description Not signed in, or the token is invalid. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Signed in but not permitted. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found (or belongs to another tenant). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request was malformed. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    import_draft_api_v1_cases__case_id__draft_recommendations_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftImport"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftOut"];
                };
            };
            /** @description Not signed in, or the token is invalid. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Signed in but not permitted. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found (or belongs to another tenant). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request was malformed. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_draft_api_v1_cases__case_id__draft_recommendations__draft_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftOut"];
                };
            };
            /** @description Not signed in, or the token is invalid. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Signed in but not permitted. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found (or belongs to another tenant). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request was malformed. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_candidates_api_v1_cases__case_id__entity_candidates_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateOut"][];
                };
            };
            /** @description Not signed in, or the token is invalid. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Signed in but not permitted. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found (or belongs to another tenant). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request was malformed. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    add_candidate_api_v1_cases__case_id__entity_candidates_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CandidateCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateOut"];
                };
            };
            /** @description Not signed in, or the token is invalid. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Signed in but not permitted. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found (or belongs to another tenant). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request was malformed. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    resolve_entity_api_v1_cases__case_id__entity_resolution_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseOut"];
                };
            };
            /** @description Not signed in, or the token is invalid. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Signed in but not permitted. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found (or belongs to another tenant). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request was malformed. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    reopen_entity_api_v1_cases__case_id__entity_resolution_reopen_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReopenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseOut"];
                };
            };
            /** @description Not signed in, or the token is invalid. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Signed in but not permitted. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found (or belongs to another tenant). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request was malformed. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    record_entity_unconfirmed_api_v1_cases__case_id__entity_resolution_unconfirmed_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UnconfirmedRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseOut"];
                };
            };
            /** @description Not signed in, or the token is invalid. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Signed in but not permitted. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found (or belongs to another tenant). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request was malformed. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_research_readiness_api_v1_cases__case_id__research_readiness_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
            /** @description Not signed in, or the token is invalid. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Signed in but not permitted. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found (or belongs to another tenant). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request was malformed. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    me_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description Not signed in, or the token is invalid. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Signed in but not permitted. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found (or belongs to another tenant). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request was malformed. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
}
