/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/audit-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Audit Events
         * @description The caller's own tenant's audit events, newest first. Reading is itself audited.
         */
        get: operations["list_audit_events_api_v1_audit_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Cases
         * @description The caller's own tenant's cases, newest first.
         */
        get: operations["list_cases_api_v1_cases_get"];
        put?: never;
        /**
         * Create Case
         * @description Create a case. Only a legal or trading name is required; the rest is tracked as gaps.
         */
        post: operations["create_case_api_v1_cases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Case
         * @description One case. Viewing Restricted case content is itself audited.
         */
        get: operations["get_case_api_v1_cases__case_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Case
         * @description Change some fields. Send `expected_version`; a stale one returns 409 and saves nothing.
         */
        patch: operations["update_case_api_v1_cases__case_id__patch"];
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Who the caller is and what they may do. Informational; grants nothing.
         */
        get: operations["me_api_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness check. Reports service status only; no case or tenant data.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuditEventOut */
        AuditEventOut: {
            /** Action */
            action: string;
            /** Actor */
            actor: string | null;
            /** Correlation Id */
            correlation_id: string;
            /** Details */
            details: {
                [key: string]: string;
            };
            /** Id */
            id: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Outcome */
            outcome: string;
            /** Resource Id */
            resource_id: string | null;
            /** Resource Type */
            resource_type: string | null;
        };
        /** CaseCreate */
        CaseCreate: {
            /** Address */
            address?: string | null;
            /** Context */
            context?: string | null;
            /** Exposure Amount */
            exposure_amount?: number | string | null;
            /**
             * Exposure Currency
             * @description ISO 4217, e.g. CAD
             */
            exposure_currency?: string | null;
            /** Industry */
            industry?: string | null;
            /** Jurisdiction */
            jurisdiction?: string | null;
            /** Legal Name */
            legal_name?: string | null;
            /** Parent Name */
            parent_name?: string | null;
            /** Registration Number */
            registration_number?: string | null;
            /** Terms */
            terms?: string | null;
            /** Trading Name */
            trading_name?: string | null;
            /** Ubo Name */
            ubo_name?: string | null;
            /** Website */
            website?: string | null;
        };
        /** CaseOut */
        CaseOut: {
            /** Address */
            address?: string | null;
            /** Context */
            context?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Exposure Amount */
            exposure_amount?: string | null;
            /**
             * Exposure Currency
             * @description ISO 4217, e.g. CAD
             */
            exposure_currency?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Industry */
            industry?: string | null;
            /** Information Gaps */
            information_gaps: components["schemas"]["InformationGap"][];
            /** Jurisdiction */
            jurisdiction?: string | null;
            /** Legal Name */
            legal_name?: string | null;
            /** Owner */
            owner: string;
            /** Parent Name */
            parent_name?: string | null;
            /** Registration Number */
            registration_number?: string | null;
            status: components["schemas"]["CaseStatus"];
            /** Terms */
            terms?: string | null;
            /** Trading Name */
            trading_name?: string | null;
            /** Ubo Name */
            ubo_name?: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version */
            version: number;
            /** Website */
            website?: string | null;
        };
        /**
         * CaseStatus
         * @description Phase 1 statuses. Later phases add research and review statuses.
         * @enum {string}
         */
        CaseStatus: "DRAFT" | "ENTITY_AMBIGUOUS" | "ENTITY_RESOLVED";
        /**
         * CaseUpdate
         * @description Partial update. `expected_version` guards against overwriting someone else's change.
         */
        CaseUpdate: {
            /** Address */
            address?: string | null;
            /** Context */
            context?: string | null;
            /** Expected Version */
            expected_version: number;
            /** Exposure Amount */
            exposure_amount?: number | string | null;
            /**
             * Exposure Currency
             * @description ISO 4217, e.g. CAD
             */
            exposure_currency?: string | null;
            /** Industry */
            industry?: string | null;
            /** Jurisdiction */
            jurisdiction?: string | null;
            /** Legal Name */
            legal_name?: string | null;
            /** Parent Name */
            parent_name?: string | null;
            /** Registration Number */
            registration_number?: string | null;
            /** Terms */
            terms?: string | null;
            /** Trading Name */
            trading_name?: string | null;
            /** Ubo Name */
            ubo_name?: string | null;
            /** Website */
            website?: string | null;
        };
        /** ErrorBody */
        ErrorBody: {
            /** Code */
            code: string;
            /** Correlation Id */
            correlation_id: string;
            /** Field Errors */
            field_errors?: components["schemas"]["FieldError"][] | null;
            /** Message */
            message: string;
            /** Retryable */
            retryable: boolean;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        /** FieldError */
        FieldError: {
            /** Field */
            field: string;
            /** Message */
            message: string;
        };
        /** Health */
        Health: {
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /** InformationGap */
        InformationGap: {
            /** Description */
            description: string;
            /** Field */
            field: string;
        };
        /** Me */
        Me: {
            /** Permissions */
            permissions: string[];
            /** Roles */
            roles: string[];
            /** Subject */
            subject: string;
            /** Tenant Id */
            tenant_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_audit_events_api_v1_audit_events_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEventOut"][];
                };
            };
            /** @description Not signed in, or the token is invalid. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Signed in but not permitted. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found (or belongs to another tenant). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request was malformed. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_cases_api_v1_cases_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseOut"][];
                };
            };
            /** @description Not signed in, or the token is invalid. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Signed in but not permitted. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found (or belongs to another tenant). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request was malformed. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_case_api_v1_cases_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaseCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseOut"];
                };
            };
            /** @description Not signed in, or the token is invalid. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Signed in but not permitted. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found (or belongs to another tenant). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request was malformed. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_case_api_v1_cases__case_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseOut"];
                };
            };
            /** @description Not signed in, or the token is invalid. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Signed in but not permitted. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found (or belongs to another tenant). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request was malformed. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_case_api_v1_cases__case_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaseUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseOut"];
                };
            };
            /** @description Not signed in, or the token is invalid. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Signed in but not permitted. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found (or belongs to another tenant). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request was malformed. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    me_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description Not signed in, or the token is invalid. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Signed in but not permitted. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found (or belongs to another tenant). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request was malformed. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
}
